common: &common
  adapter: postgresql
  username: <%= ENV['PG_USER'] %>
  password: <%= ENV['PG_PASSWORD'] %>

development:
  adapter: postgresql
  encoding: unicode
  port: 5432
  host: localhost
  pool: 5
  username: admin
  password:  
  database: lc_dev

staging:
  <<: *common
  database: lc_staging

test:
  <<: *common
  database: lc_test

production:
  <<: *common
  database: lc_production
