common: &common
  adapter: postgresql
  username: <%= ENV['PG_USER'] %>
  password: <%= ENV['PG_PASSWORD'] %>

development:
  <<: *common
  database: lc_dev

test:
  <<: *common
  database: lc_test

production:
  <<: *common
  database: lc_production
