development:
  bucket: finalforms
  access_key_id: AKIAJSXMZM56M7MPW76A
  secret_access_key: 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

test:
  bucket: finalforms-test
  access_key_id: AKIAJSXMZM56M7MPW76A
  secret_access_key: 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
ction:
  bucket: finalforms
  access_key_id: AKIAJSXMZM56M7MPW76A
  secret_access_key: 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

