# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).

# Seed Users
user = User.create(
                   first_name: 'Joe',
                   last_name: 'Admin',
                   email: 'admin@admin.asdf',
                   role: 'admin',
                   password: "AdminFF",
                   password_confirmation: "AdminFF",
                   )
user.confirm!

user = User.create(
                   first_name: 'Joe',
                   last_name: 'Buyer',
                   email: 'buyer@buyer.asdf',
                   role: 'buyer',
                   password: "BuyerFF",
                   password_confirmation: "BuyerFF",
                   )
user.confirm!
p = BuyerProfile.create(
                   name: "Williams College",
                   street_address_1: "355 Auburn St",
                   city: "Boulder",
                   state: "CO",
                   zip: "80305",
                   phone: "440-796-7082",
                   description: "I am a test buyer",
                   user_id: user.id
                   )

user = User.create(
                   first_name: 'Joe',
                   last_name: 'Producer',
                   email: 'producer@producer.asdf',
                   role: 'producer',
                   password: "ProducerFF",
                   password_confirmation: "ProducerFF",
                   )
user.confirm!
ProducerProfile.create(
                   name: "Bellview Farms",
                   street_address_1: "40 Harvard Rd",
                   city: "Boulder",
                   state: "CO",
                   zip: "80305",
                   phone: "440-796-7082",
                   description: "I am a test producer",
                   user_id: user.id
                   )

Category.createTree({"Meat" =>
["Vension",
"Turkey",
"Rabbit",
"Pork",
"Other Poultry",
"Ostrich",
"Lamb",
"Goose",
"Goat",
"Game Birds",
"Elk",
"Duck",
"Chicken",
"Bison",
"Beef"],
  "Dairy and Soy" =>
["Yogurt",
"Soy Products",
"Milk",
"Ice Cream",
"Egg Nog",
"Cream",
"Cheese",
"Buttermilk",
"Butter"],
  "Eggs" =>
["Quail Eggs",
"Duck Eggs",
"Chicken Eggs"],
  "Fruit" =>
["Quince",
"Plums",
"Pears",
"Peaches",
"Nectarines",
"Melons",
"Grapes",
"Frozen Fruit",
"Currants",
"Cider and Juice",
"Cherries",
"Berries",
"Apricots",
"Apples"],
  "Vegetables" =>
["Turnips",
"Tomatoes",
"Sunchokes",
"Squash",
"Sprouts",
"Salsify",
"Rutabaga",
"Ramps",
"Radishes",
"Potatoes",
"Peppers",
"Peas",
"Parsnips",
"Onions",
"Okra",
"Mushrooms",
"Mixed Box",
"Microgreens",
"Leeks",
"Kohlrabi",
"Herbs",
"Hay",
"Greens",
"Garlic",
"Frozen Vegetables",
"Flowers",
"Fennel",
"Eucalyptus",
"Eggplant",
"Cucumbers",
"Corn",
"Celery",
"Cauliflower",
"Carrots",
"Cardoons",
"Cabbage",
"Brussels Sprouts",
"Broccoli",
"Beets",
"Beans",
"Asparagus",
"Artichokes"],
  "Pantry" =>
["Vinegar",
"Syrup",
"Sauces",
"Relishes and Salsas",
"Pickled Items",
"Oils",
"Jams and Spreads",
"Honey",
"Granola",
"Grains",
"Dried Beans",
"Condiments",
"Coffee",
"Applesauce"],
  "Baked Goods" =>
["Pies",
"Pastries",
"Granola",
"Cupcakes",
"Cookies",
"Cakes",
"Brownies",
"Bread",
"Bars"],
  "Seafood" =>
["Trout",
"Tilapia",
"Shellfish",
"Bass"]
                    })
